####################################################################
####################################################################
####################################################################
#██    ██ ██    ██ ██      ██ ███    ███  █████  ██ ████████ ███████
#██    ██ ██    ██ ██      ██ ████  ████ ██   ██ ██    ██    ██
#██    ██ ██    ██ ██      ██ ██ ████ ██ ███████ ██    ██    █████
#██  ██   ██  ██  ██      ██ ██  ██  ██ ██   ██ ██    ██    ██
#████     ████   ███████ ██ ██      ██ ██   ██ ██    ██    ███████
####################################################################
####################################################################
####################################################################

#This Plugin is from EliVB

#This is a Plugin like DonutSMP Sell, you can change all of the messages.
#For more Premium Skripts or Plugins join our Discord: "https://discord.gg/V3fcWZrccj"

#permissions
#sell.reload - Permission to reload the plugin
#sell.use - Permission to use the /sell command
#sell.sellaxe - Permission to use the /sellaxe command
#sell.setworth - Permission to use the /setworth command

#Plugin Placeholders
#%donutsell_total_items% - The total amount of sold items
#%donutsell_total_sold% - The total price of the sold items
#%donutsell_formatted_total% - The formatted total price of the sold items
#%donutsell_sold_money_1-100% - Rank of total sold
#%donutsell_sold_items_1-100%- Rank of total items
#%donutsell_potion_me_money% - Rank of the player by money sold
#%donutsell_potion_me_items% - Rank of the player by items sold

#The main command Sell will always be registered
command-aliases:
  - sellgui

worth-lore:
  enabled: true
  lore-format: "&7Worth: &#0bf52b%price%"

shulker-support:
  enabled: true

don-t-show-gui: #Here you can disable worth lore in guis
  - "&8ʙᴜʏ"

economy:
  provider: VAULT
  currency-format: "#,##0.##"
  abbreviations:
    enabled: true #Accept 100k, 10k, 1m, etc... in the sign of price.
    formats:
      - 'K'
      - 'M'
      - 'B'
      - 'T'

progress-bar:
  loading-color: '&f'
  complete-loading-color: '&#20f706'
  bar-length: 21
  bar-symbol: '&m '

#This Plugin supports custom sounds, you can change them here
sounds:
  sell-success: "ENTITY_EXPERIENCE_ORB_PICKUP"
  no-sellable-items: "ENTITY_VILLAGER_NO"
  plugin-reloaded: "ENTITY_PLAYER_LEVELUP"
  click-sound: "UI_BUTTON_CLICK"
  setworth-success: "ENTITY_PLAYER_LEVELUP"
  setworth-error: "ENTITY_VILLAGER_NO"